<!--异常信息头-->
【异常时间】：2018-10-30 17:56:12,912 [11] ;
【异常级别】：ERROR 
【抛出信息】：发生了未知内部错误 
【异常类型】：DivideByZeroException 
【异常信息】：Attempted to divide by zero. 
【堆栈调用】：   at LoggerDemo.Controllers.HomeController.Index() in E:\Cui\LoggerDemo\LoggerDemo\Controllers\HomeController.cs:line 16
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 
 <!--异常信息尾部-->
